<template>
  <div class="w-full overflow-x-auto">
    <h1 class="text-4xl font-bold my-16 ml-10">Empresa</h1>

    <div class="mx-8">
      <Table :columns="columns" :data="data" />
      <!-- <DataTable :columns="columns" :data="data" /> -->
    </div>
  </div>
</template>

<script setup>
import Table from "@/components/Table.vue";
import DataTable from "@/components/DataTable.vue";

const columns = [
  { name: "id", id: "id" },
  { name: "name", id: "name" },
  { name: "user_id", id: "user_id" },
  { name: "area_id", id: "area_id" },
  { name: "post_id", id: "post_id" },
  { name: "status_id", id: "status_id" },
  { name: "company_id", id: "company_id" },
  { name: "evaluation_id", id: "evaluation_id" },
];

const data = [
  {
    id: 1,
    name: "Michelle Vega-Guajardo Vásquez",
    user_id: 1510,
    area_id: 83,
    post_id: 0,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 2,
    name: "Anaís Jara",
    user_id: 1514,
    area_id: 83,
    post_id: 1,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 3,
    name: "Sofía Agustina Castro Soto",
    user_id: 1515,
    area_id: 83,
    post_id: 2,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 4,
    name: "Juan Claudio Cruz Alfaro",
    user_id: 1517,
    area_id: 83,
    post_id: 3,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 5,
    name: "Mauricio Martín Espinoza Vilches",
    user_id: 1530,
    area_id: 83,
    post_id: 4,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 6,
    name: "Nora Flores",
    user_id: 1539,
    area_id: 83,
    post_id: 5,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 7,
    name: "José René Torres Mora",
    user_id: 1541,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 8,
    name: "María Juana Saavedra Garrido",
    user_id: 1545,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 9,
    name: "Jorge Fernando Chandía Madrid",
    user_id: 1547,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 10,
    name: "Gloria Alarcón",
    user_id: 1549,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 11,
    name: "Rosa Emma Alarcón González",
    user_id: 1553,
    area_id: 83,
    post_id: 10,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 12,
    name: "Graciela Guzmán",
    user_id: 1557,
    area_id: 83,
    post_id: 11,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 13,
    name: "Juana Rubio",
    user_id: 1663,
    area_id: 83,
    post_id: 11,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 14,
    name: "Albertina Núñez",
    user_id: 1665,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 15,
    name: "Alice Sepúlveda Alvarado",
    user_id: 1666,
    area_id: 83,
    post_id: 1,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 16,
    name: "Diego Alex Becerra Rojas",
    user_id: 1676,
    area_id: 83,
    post_id: 11,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 17,
    name: "María Sofía Montenegro Cerda",
    user_id: 1682,
    area_id: 83,
    post_id: 16,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 18,
    name: "Dionisio Rebolledo-Toro",
    user_id: 1687,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 19,
    name: "Felipe Carlos Vera Contreras",
    user_id: 1689,
    area_id: 83,
    post_id: 11,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 20,
    name: "Manuel Contreras",
    user_id: 1696,
    area_id: 83,
    post_id: 11,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 21,
    name: "Patricio Rafael Riquelme Ayala",
    user_id: 1697,
    area_id: 83,
    post_id: 11,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 22,
    name: "Mariana Mamani Jara",
    user_id: 1700,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 23,
    name: "Rosa Ximena Véliz Pizarro",
    user_id: 1701,
    area_id: 83,
    post_id: 11,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 24,
    name: "Daniel Jean Meléndez Godoy",
    user_id: 1704,
    area_id: 83,
    post_id: 4,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 25,
    name: "Andrea María Quiroz Fuentealba",
    user_id: 1706,
    area_id: 83,
    post_id: 0,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 26,
    name: "Johana Carmen Valenzuela Bravo",
    user_id: 1707,
    area_id: 83,
    post_id: 1,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 27,
    name: "Marisol Díaz Saavedra",
    user_id: 1708,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 28,
    name: "Martina Teresa Escobar Peña",
    user_id: 1709,
    area_id: 83,
    post_id: 4,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 29,
    name: "Oscar Retamal-Lobos González",
    user_id: 1713,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 30,
    name: "Martín Cid",
    user_id: 1725,
    area_id: 83,
    post_id: 29,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 31,
    name: "Máximo Santibáñez",
    user_id: 1727,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 32,
    name: "Andrea López",
    user_id: 1728,
    area_id: 83,
    post_id: 31,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 33,
    name: "René Ramón Henríquez Ibarra",
    user_id: 1729,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 34,
    name: "René Carvajal González",
    user_id: 1733,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 35,
    name: "Richard Domínguez Palma",
    user_id: 1735,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 36,
    name: "Adrián Bustos Aguilar",
    user_id: 1742,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 37,
    name: "Misael Godoy Herrera",
    user_id: 1743,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 38,
    name: "Raúl Sebastián Moraga Mena",
    user_id: 1745,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 39,
    name: "Jonathan René Díaz Soto",
    user_id: 1748,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 40,
    name: "William José Muñoz Pérez",
    user_id: 1750,
    area_id: 83,
    post_id: 4,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 41,
    name: "Abel Víctor Almonacid García",
    user_id: 1752,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 42,
    name: "Marcela Angélica Andrade-Mora Olguín",
    user_id: 1755,
    area_id: 83,
    post_id: 41,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 43,
    name: "Cristian Rubén Videla Vergara",
    user_id: 1759,
    area_id: 83,
    post_id: 42,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 44,
    name: "Victoria Arce",
    user_id: 1768,
    area_id: 83,
    post_id: 11,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 45,
    name: "Verónica Llanos Ortega",
    user_id: 1772,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 46,
    name: "Julieta Yessenia Rodríguez-Ortiz Mansilla",
    user_id: 1778,
    area_id: 83,
    post_id: 4,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 47,
    name: "Ángel Manuel Álvarez Aguilera",
    user_id: 1781,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 48,
    name: "Ronald Cisterna Rojas",
    user_id: 1783,
    area_id: 83,
    post_id: 47,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 49,
    name: "Víctor Ojeda-Durán Ríos",
    user_id: 1789,
    area_id: 83,
    post_id: 11,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 50,
    name: "Aurora Contreras Yáñez",
    user_id: 1792,
    area_id: 83,
    post_id: 5,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 51,
    name: "Roberto Julián Beltrán Cerda",
    user_id: 1802,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 52,
    name: "Catalina Nicole Torres Collao",
    user_id: 1805,
    area_id: 83,
    post_id: 51,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 53,
    name: "Domingo Hernán Jerez Muñoz",
    user_id: 1821,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 54,
    name: "María Salazar Carrasco",
    user_id: 1822,
    area_id: 83,
    post_id: 1,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 55,
    name: "Amaya María Veas Reyes",
    user_id: 1824,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 56,
    name: "Valentina San Martín Mora",
    user_id: 2352,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 57,
    name: "Luis Jorge Pinto Zamora",
    user_id: 2354,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 58,
    name: "Germán Sebastián Ramos Maturana",
    user_id: 3169,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 59,
    name: "José Mora",
    user_id: 4815,
    area_id: 83,
    post_id: 2,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 60,
    name: "Santiago Marchant",
    user_id: 6275,
    area_id: 83,
    post_id: 6,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 61,
    name: "Trinidad Liliana Retamal Ríos",
    user_id: 7064,
    area_id: 83,
    post_id: 1,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 62,
    name: "Andrés Arancibia Ojeda",
    user_id: 7065,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 63,
    name: "Fabiola Rojas Tello",
    user_id: 7074,
    area_id: 83,
    post_id: 2,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 64,
    name: "Emma Rivera Martínez",
    user_id: 7076,
    area_id: 83,
    post_id: 2,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 65,
    name: "Trinidad Santana Contreras",
    user_id: 7077,
    area_id: 83,
    post_id: 2,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 66,
    name: "Gustavo Ignacio Alarcón Cabrera",
    user_id: 7091,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 67,
    name: "Raquel Jerez",
    user_id: 7092,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 68,
    name: "Matías Patricio Toro Mellado",
    user_id: 7093,
    area_id: 83,
    post_id: 2,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 69,
    name: "Trinidad Pereira",
    user_id: 7095,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 70,
    name: "Iris Soto",
    user_id: 7099,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 71,
    name: "Kimberly Rayén Parra Quintanilla",
    user_id: 7101,
    area_id: 83,
    post_id: 2,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 72,
    name: "Alejandra Mónica Quijada Carrasco",
    user_id: 7104,
    area_id: 83,
    post_id: 2,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 73,
    name: "Mary María Jiménez Tapia",
    user_id: 7107,
    area_id: 83,
    post_id: 1,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
  {
    id: 74,
    name: "Valentina Carmen Bahamonde Fernández",
    user_id: 7116,
    area_id: 83,
    post_id: 9,
    status_id: 1,
    company_id: 24,
    evaluation_id: 0,
  },
];
</script>
